import pandas as pd

gformb = pd.read_csv("(responses) COVID-19 Chronicles electronic file upload form.csv")
gforma = pd.read_csv("Covid-19 Chronicles contributor form (Responses).csv")

merged = pd.merge(gformb, gforma, how='left', on=['Email Address'])
merged.to_csv("merged_responses.csv", index=False)

merged_csv = pd.read_csv("merged_responses.csv",low_memory=False)
renamed = merged_csv.rename(columns={'Nanci confirm Deed of Gift is complete':'nanci_checkB1',
    'What copyright choice did the donor make in the deed?':'copyright',
    'Nanci confirm data and files are complete and as expected':'nanci_checkB2',
    'IF donor already has an agent record in ASpace, what is its URI? (last 4 digits at the end of the URL for the agent page)':'agent_id',
    'Timestamp_x':'timestampB',
    'Email Address':'email',
    'File 1: Briefly describe this file or zipped folder of files (250 characters, or about 40 words maximum)':'file1_desc',
    'File 1: When was this item created?':'file1_date',
    'File 1: Upload your file or zipped folder of files':'file1_upload',
    'Do you have another file to upload?':'anotherfile1',
    'File 2: Briefly describe this file or zipped folder of files (250 characters, or about 40 words maximum)':'file2_desc',
    'File 2: When was this item created?':'file2_date',
    'File 2: Upload your file or zipped folder of files':'file2_upload',
    'Do you have another file to upload?.1':'anotherfile2',
    'File 3: Briefly describe this file or zipped folder of files (250 characters, or about 40 words maximum)':'file3_desc',
    'File 3: When was this item created?':'file3_date',
    'File 3: Upload your file or zipped folder of files':'file3_upload',
    'Do you have another file to upload?.2':'anotherfile3',
    'File 4: Briefly describe this file or zipped folder of files (250 characters, or about 40 words maximum)':'file4_desc',
       'File 4: When was this item created?':'file4_date',
       'File 4: Upload your file or zipped folder of files':'file4_upload',
       'Do you have another file to upload?.3':'anotherfile4',
       'File 5: Briefly describe this file or zipped folder of files (250 characters, or about 40 words maximum)':'file5_desc',
       'File 5: When was this item created?':'file5_date',
       'File 5: Upload your file or zipped folder of files':'file5_upload',
       'Do you have another file to upload?.4':'anotherfile5',
       'File 6: Briefly describe this file or zipped folder of files (250 characters, or about 40 words maximum)':'file6_desc',
       'File 6: When was this item created?':'file6_date',
       'File 6: Upload your file or zipped folder of files':'file6_upload',
       'Do you have another file to upload?.5':'anotherfile6',
       'File 7: Briefly describe this file or zipped folder of files (250 characters, or about 40 words maximum)':'file7_desc',
       'File 7: When was this item created?':'file7_date',
       'File 7: Upload your file or zipped folder of files':'file7_upload',
       'Do you have another file to upload?.6':'anotherfile7',
       'File 8: Briefly describe this file or zipped folder of files (250 characters, or about 40 words maximum)':'file8_desc',
       'File 8: When was this item created?':'file8_date',
       'File 8: Upload your file or zipped folder of files':'file8_upload',
       'Do you have another file to upload?.7':'anotherfile8',
       'File 9: Briefly describe this file or zipped folder of files (250 characters, or about 40 words maximum)':'file9_desc',
       'File 9: When was this item created?':'file9_date',
       'File 9: Upload your file or zipped folder of files':'file9_upload',
       'Do you have another file to upload?.8':'anotherfile9',
       'File 10: Briefly describe this file or zipped folder of files (250 characters, or about 40 words maximum)':'file10_desc',
       'File 10: When was this item created?':'file10_date',
       'File 10: Upload your file or zipped folder of files':'file10_upload',
       'Have you uploaded all of your files, and are you ready to submit?':'readytosubmit',
       'Add any additional questions or comments you have for archives staff (optional)':'comments',
       'Nanci has reviewed & corrected metadata, it is accurate & complete':'nanci_checkA',
       'Timestamp_y':'timestampA',
        'What is your preferred first or given name(s)?':'first_name',
       'What is your preferred surname or family name(s)?':'last_name',
       'Please write out your full name exactly as you would like it to appear in our catalog':'full_name',
       'What is your legal name, if different from your preferred name?':'legal_name',
       'What is your Smith College affiliation?':'affiliation',
       'What is your current geographic location?':'where_living',
       'Please consider writing a brief biographical statement (up to 1500 characters/about 250 words) that would provide important background to future researchers looking at your contribution':'bioghist',
       'Did you create the materials you want to contribute? (check all that apply)':'created',
       'Does your contribution contain personal medical information (information about diagnoses, treatments, etc.) about anyone other than yourself?':'med_info',
       'All materials you contribute will be cataloged online, and will be available to the public. However, you can control whether they are made available to the public immediately or after 5 years.':'access',
       'Do you have digital files (documents, photographs, recordings, etc.) that you want to contribute to this project?':'digital_files_yn',
       'Do you have online content (your own or your Smith-affiliated group\'s blog, social media account, etc.) that you would be interested in having copied for the archives as part of this project?':'online_content_yn',
       'Briefly describe the digital files that you want to contribute':'content_description',
       'Approximately how many files do you want to contribute?':'number_of_files',
       'What type of files do you want to contribute? (check all that apply)':'file_types',
       'Do you have physical materials (writing, photographs, sketches, etc.) that you would like to contribute?':'physical_material_yn',
       'Briefly describe the physical materials you want to contribute':'phys_content_description',
       'Please add any additional questions you have for archives staff':'questions'})
renamed.to_csv("merged_responses_newheaders.csv", index=False)
